spring: 
  data: 
    mongodb: 
      uri: mongodb://chetan:chetan@ds161039.mlab.com:61039/kurvatch_dev
---
endpoints: 
  info: 
    enabled: true
--- 
management: 
  health: 
    mongo: 
      enabled: true
  security: 
    enabled: false
--- 
spring: 
  rabbitmq: 
    host: salamander.rmq.cloudamqp.com
    password: 4IzsLhDOK1Pb9tTcgsJmIZuqMrrgJgBa
    username: isedcdxu
    port: 5672
    virtual-host: isedcdxu
